language: go
go:
- 1.7
script:
- make validate-syntax
- make lint
- make test
deploy:
  provider: s3
  access_key_id:
    secure: "JQD5ipVmLhAZYQWiNAapzJ7OLz/DS3YAEkRVemx+K3fQqRPAxZuS08SkiFIbsx0xbLQpkZBiZMXi3qi14cVWSvok3pswfh/K4CN6JXi0aAqIuDyzGwsr2AMW3gz7YHOW4IbjC9iIr0xTCau3kPUH1YEHbQRICTspWvRAO3mJRGsUZ2vZ44K4prceo+dAzv70XZqjOorbMI+aikMAmbuUZeItZBPPsQoCJs5LEsciRXOvFSmGpDyAEB/g8vt2W64EBFvCfoKqCUF6KgdjpY2nnL3ksTmgyFv/hV8S7LpZdG9E/03KSafP8G7CpCQTnTbE6yKN9xjXvCVOKBLVmy+s7+zXUN9hdKuNn6mO4b5hp+ofEyq5t9GJkvrU5MkwC/EK3qNM64ahQ7L6CQRINK+Zp/D8kD0B73upNoja0JSkJPelqqMwkl8SfIFEYWyNtNjaQffbJDB0NvmIwt2GIy2HtXtfoQ6cizwz8q1iaS62C/XXDtbuaDq3FfP6ECo0BGKEi0SoJVVZa8Nh0E9Y/rUVISo2rs3xmRM9O54rLnfr9TsvxANYWMVmBo9HMS7V9Mp82I77ydtOIAHXR/SHbO9pFRx7my+1OFX02JmuhMJ3mnXl6es6heB+IwZF+qylpX3gl2wI95DAw5L5lQWGiyBso9YSJqnN1gtkp5bACNIH1gw="
  secret_access_key:
    secure: "pxfkBUcT6TqiI7qmPSpYGfghI568sfMD34btmuveJUW9DsUusfA3jJ21rqEXr1zrH3CkkV0uSmLh4scngrjW74I6G5kdrx5FOPztOsAr2vQ98Q4zZXVEcJE1OP8R43bJrP4B545ci/CbEUiF0bHhbriTprsI2ee6E1lODYp5wAM97eE4y3pzeClVNfde2l9ZmYwNOBygi/J8rC1+ne1iLw451xOHCvAqkn2xOHj9Sl4Yr6v8ajdpbwRt/lUCh5yAgVgXusviMP/nV11w8gtj5YIb//MLhpHHqf3wg79fYqP3BgMNbxBk6VWHDswHt0NS66x+E+Xmr6IhvBu3G0oQWvfpxs8kn7jwcggRjN+rWbN6r1f8cnoP2/Q3u7DEwYgGq3mKgBKbeC6nxvOWIisLqXC14JATrZk0HiCWi40q6UrmWwOkoB8jPHHfME7+sYiSYMMR3EHX7HO6rGeEJ6fmScCi8DxBFrJjXEMTtj9E2BkFZQW+NSPSxkO459qB7vHjGLevwRLQ7Sl5tkr9Wrjo90fvDK4jDjxvUCFwDAmoRX93pE++7pJV/xEzuyFJXRnMagXgWWKmWWBmLSwDZf7qoEQnCqLFmpPs0l7AQymVGXifI140uLzoWKHTRROMmdWDS8e53a96lMxgSLG2saTBVZKusR7BYFRs4kl3XSebzTo="
  bucket: awsopsassistant-experiment-artifact
  region: ap-southeast-2
  local-dir: experiment-src
  acl: 'private'
  on:
    repo: ZenChair/aws-ops-assistant
