language: go
go:
- 1.7
before_script:
- nvm install v6
script:
- make validate-syntax
- make lint
- make test
deploy:
  provider: s3
  access_key_id:
    secure: mHL/tHf/zBP6b1zbmWMPJHW6dyWu5zg2wCnDAixsr7DuOdM3xjeweieZoG999PpPLKK+8ibCeXdCNevbEXXRp3zvaTJ76+hYoyBnd4nKHBW0+KLSsxuZnPwlgsoZiuWC7CAqZXTrjxxbr/hrZAfNNp89yEnGiFc6gao7n4tF4kd0cVsS5nGee/FMxAClIjq/PVQAzAGJzBZW6iKDA67aiM/zVRayogZ/VMcterECkOspeOm9q/ocwCs1Bs0VIOnjCCTu5t8C2sTYT4tuLk0uebxtu5TLaYOkcLRxEJcDyeZEsgUAUi56HJD42YBXb9INRZyb6AIVBd7b+gSRHWPvvweMVdsrjy7pyoucUtalaWx7CgJX1RSO302suIumA2qm9fJn/paDk1BEVoBS5352ZgNmtkQGrym17erkOeLrkwJxEoxovkJNvtZIxEmJSsa2WazCTGtCCCfg+UQ6aRV2iYKhFtSrBZbyxfJgeN4qzfP0logd7DznZNgtmeGD1gRdBfdb/EltchO80EnT9kBhSWZ2G2wUKE5bxIir3YtNlY+Sr9N8U/k1Rwq4pV/Q/Swihd8gM0CFLbZ9B3bjm7k0W3dJy2rPrU9nJptd9ac8BfpU3vjWZAaWddDHys4KMU7Oa2gw9RhDIBkx4/DsSYXCHnzVi4e3zosfANWMHVVJn9k=
  secret_access_key:
    secure: u0dTcvTMu531yws180YhevbVfFiqfDfSzGKXV77aE54PYjDrBKRIVNanqoPG6+HxggYP3qZpcQe/ismtNVrytihIWhxzK2SMO+Sjptl3cymcXJBRZI98hSpak3qFf9eYtf4yI6VBbfXkai/tUmKTdsxaZPfMcn7Mabw6/CEhlI0cUeUf5k5tDlauVP88BGeb5a4sEb7rvtcqhhXtxCkn/tPxe48nqkkxf7BjSFHgNarTAt5f/pFPfUXxGamrxnH/DzRnf6vWG8IaWUITeiAE1R4CQdW3LEmzolWHV8d6W1eDfQDy0RdXIqfWeI25uCHEHc4YbNEXhGTmxvnm3jr3JoFUZGZPBI9MY4sn4lvg/KAJkbMS6jCdiedCbDr1hPljeMJ1LGaC8uOF1wsuUba5wppCd1TxQo1K2957iQvN74NKLFIElk6b376gF5bUPPA4UOwOgeW6QFArrYEXrgbhexjYisbYj8plc5MklhvDAmoQBjn7vCt7UHJdB98gBz3q4RAG+uJa+e5JG+DtfGIig92SB94KBZca9QsAnE7L6KCbdQe97jlRzOFZSw9cItUCMnIqua09/dI++Mq0pNbkROnPdEmCgqVmU7KiqEZdwFsqUFofacv7BOq+QFXZJr0nSTQkj5314gv0Uo1C6KDFEpnRQqc1etMUsaJ3pn8zQp8=
  bucket: awsopsassistant-experiment-artifact
  region: ap-southeast-2
  local-dir: experiment-src
  acl: private
  on:
    repo: ZenChair/aws-ops-assistant
notifications:
  slack:
    rooms:
      secure: W6HTg7tIlUFRpLhVsCS30tH328RTbltXcclN40EcdWGvxswDdWn+3BhCWY43ba4hdd5FY3oRE1IDazH69RBPndpn9BSB76rBAbfPYBcw66mchL/sbY3zVuXVVN1Bvc6gfhLvgmSemsikl+MmfgBNFodX+ftKR7C4PoOWBYWBlj8ffdypiFb5szo9mIcI5RLPHaI/XMOfBFaD2QSfBcsQULya0U520p1VGYa0OZzo2uo2sWUQVHg7UM7dsqDGEzzDFjSihn+o5rpTP8AyOXRFJx89ph20Ja79clOiS8KWIaGuQmojDKEYMAmVX+vE3peE1nxO/HZP2kvA0l8sADGOlfaqKFFxpnAwLxxIf/fkBBKRNrVqpmGSyE/o+/PVz9yYFXlxfezI2kXSFlNmusTEr8MhU5xJb44BQUfCr/peRxSJjN3jR0Qe33DiB1DirDcpAHfopxPYkBpKXmlCams8L9FDslB+glx2GZlNxkPkBPWWwD+Oe1L9tSjQLqcqkigIQ0JHnpaiLUuTqj3Nzzdq5tUCjgVhhOD1Zqae4xeyKGiF1MzXICJpYCVpzeAgYEDmtHJcWpXLMTs02FGiJ7YWZ875S0xyQR14S4Z8lbIKWWXX9dqrVmU1zBNFaGdiW+TomwFjuUjYAzI4cjGfdBoftEPaG5MScTqTXCLu7+MqiL8=
    on_success: change
    on_failure: always
